### ISSUE TITLE
can't build ch3

### ISSUE THREAD

**Issue by HakeemG** [elegant-scipy/elegant-scipy#335]
I have been trying to build ch3 but I keep running into the following issue:

PYTHONWARNINGS="ignore" notedown --timeout 600 --match python --run markdown/ch3.markdown --output ipynb/ch3.ipynb
jupyter nbconvert --to html ipynb/ch3.ipynb --stdout > html/ch3.html
[NbConvertApp] Converting notebook ipynb/ch3.ipynb to html
tools/html_image_embedder.py html/ch3.html > html/ch3.html.embed && mv html/ch3.html.embed html/ch3.html
Traceback (most recent call last):
  File "tools/html_image_embedder.py", line 44, in <module>
    with urllib.request.urlopen(src) as response:
  File "/home/ec2-user/anaconda3/envs/elegant-scipy/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/ec2-user/anaconda3/envs/elegant-scipy/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/home/ec2-user/anaconda3/envs/elegant-scipy/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/ec2-user/anaconda3/envs/elegant-scipy/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/home/ec2-user/anaconda3/envs/elegant-scipy/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/ec2-user/anaconda3/envs/elegant-scipy/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
make: *** [html/ch3.html] Error 1

**Comment by jni** [comment]
@HakeemG thanks very much for the report! One of the images linked from the html page has moved, which caused the error. Please see #336 for the fix. (And `git pull` to get the latest master!)
