### ISSUE TITLE
Make htmlbook fails

### ISSUE THREAD

**Issue by HakeemG** [elegant-scipy/elegant-scipy#337]
I have been trying to build html book but I have been runing into the following issue:

$ make htmlbook
mkdir -p ./html ./ipynb ./htmlbook ./figures/generated
tools/link.py data ./ipynb/data
tools/link.py style ./ipynb/style
PYTHONWARNINGS="ignore" notedown --timeout 600 --match python --run markdown/preface.markdown --output ipynb/preface.ipynb
git submodule update --init --recursive
Submodule path 'OReilly_HTMLBook': checked out '14fdeaa3d042307dd9369495a2316bed97c02d76'
mkdir -p ./htmlbook/downloaded
ln -sf /Users/hakeemg/Documents/elegant-scipy/figures ./htmlbook/figures
ln -sf /Users/hakeemg/Documents/elegant-scipy/images ./htmlbook/images
jupyter nbconvert --to=mdoutput --output="preface.html" --output-dir=./htmlbook ipynb/preface.ipynb
Traceback (most recent call last):
  File "/Users/hakeemg/anaconda3/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/Users/hakeemg/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/hakeemg/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/hakeemg/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 325, in start
    self.convert_notebooks()
  File "/Users/hakeemg/anaconda3/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 482, in convert_notebooks
    cls = get_exporter(self.export_format)
  File "/Users/hakeemg/anaconda3/lib/python3.6/site-packages/nbconvert/exporters/base.py", line 110, in get_exporter
    % (name, ', '.join(get_export_names())))
ValueError: Unknown exporter "mdoutput", did you mean one of: asciidoc, custom, html, latex, markdown, notebook, pdf, python, rst, script, slides?
make: *** [htmlbook/preface.html] Error 1

**Comment by jni** [comment]
@HakeemG why do you need to make the htmlbook? This is a specific format for O'Reilly publishing. You should be fine with `make html`...?

**Comment by HakeemG** [comment]
I am just looking to build all of the book to have it all in one file. I figure since it is provided how to build it, I can do it.

**Comment by jni** [comment]
@HakeemG we probably won't officially support the htmlbook pipeline — I consider that downstream work for O'Reilly, and I only worked with it a couple of times. However after a quick search I found this, probably an undeclared dependency:

https://github.com/Carreau/jupytercontrib

Try installing it and see if it helps?

**Comment by HakeemG** [comment]
Thank you @jni for all your help, I will try to figure out my self.
